#!/bin/bash

set -e
set -x

: ${CATTLE_TEST_AGENT_IMAGE:='docker:cattle/test-agent:v7'}
: ${PHANTOMJS_BIN:='/usr/local/bin/phantomjs'}

export CATTLE_TEST_AGENT_IMAGE PHANTOMJS_BIN

cd $(dirname $0)/..

build_env()
{
    ./scripts/build-env 
}

teardown_env()
{
    popd
    ./scripts/build-env -d
}

run_tests()
{
    pushd ./tests/validation
    tox 
}

if [ -z "${CATTLE_TEST_URL}" ]; then
    trap "teardown_env" EXIT TERM ERR
    build_env

    export CATTLE_TEST_URL=http://$(gce-10acre-ranch -c cattle-$(id -un) -i):8080
    echo "\nGiving hosts time to register"
    sleep 30
else
    echo "Using set CATTLE_TEST_URL env var: ${CATTLE_TEST_URL} for tests"
fi


run_tests
